import pandas as pd
df = pd.read_csv(r"C:\Users\VGm\Desktop\vendite_storiche.csv")
print("=== PRIME RIGHE ===")
print(df.head())
print("/n=== INFO ===")
print(df.info())
print("/n=== DESCRIBE ===")
print(df.describe())
df["Vendite"] = df["Vendite"].fillna(df["Vendite"].mean())
df = df.drop_duplicates()
df["Data"] = pd.to_datetime(df["Data"])
df["Vendite"] = pd.to_numeric(df["Vendite"])
df["Prezzo"] = pd.to_numeric(df["Prezzo"])
print("/n === DATI PULITI ===")
print(df.head())
totali = df.groupby("Prodotto")["Vendite"].sum()
print("/n=== VENDITE TOTALI PER PRODOTTO ===")
print(totali)
print("/nProdotto più venduto:")
print(totali.idxmax())
print("/nProdotto meno venduto:")
print(totali.idxmin())
media_giornaliera = df.groupby("Data")["Vendite"].sum().mean()
print("/nMedia vendite giornaliere")
print(round(media_giornaliera, 2))
df.to_csv("vendite_pulite.csv", index=False)
print("Analisi completata con successo!")
print("/nProgetto completato!")